sudo: false

language: node_js
node_js:
  - '10'
  - '12'
  - '14'

os:
  - linux
  - osx

script:
  - travis_retry npm run test-only
  - not grep -R --exclude-dir=fixtures \\.only ./tests

jobs:
  include:
    - stage: other
      script: npm run format:check
      node_js: lts/*
      name: Lint
